//Copyright (c) 2016 Steven Yan and Joshua Lewis Tyler
//Licensed under the MIT license
//See LICENSE.txt

//File to translate relevant defines from "Teeeny Style" to "CMSIS Style"
//Note some of these need to be undefined due to an incompatible define in <MKL46Z4.H>

#include <MKL46Z4.H>

#define USB0_ENDPT0 USB0->ENDPOINT[0].ENDPT
#define USB0_ENDPT1 USB0->ENDPOINT[1].ENDPT

#define IRQ_USBOTG USB0_IRQn
#define NVIC_ENABLE_IRQ NVIC_EnableIRQ
#define NVIC_SET_PRIORITY NVIC_SetPriority

#undef USB_ENDPT_EPSTALL
#define USB_ENDPT_EPSTALL USB_ENDPT_EPSTALL_MASK
#undef USB_ENDPT_EPRXEN
#define USB_ENDPT_EPRXEN USB_ENDPT_EPRXEN_MASK
#undef USB_ENDPT_EPTXEN
#define USB_ENDPT_EPTXEN USB_ENDPT_EPTXEN_MASK
#undef USB_ENDPT_EPHSHK
#define USB_ENDPT_EPHSHK USB_ENDPT_EPHSHK_MASK
#define USB0_CTL USB0->CTL
#undef USB_CTL_USBENSOFEN
#define USB_CTL_USBENSOFEN USB_CTL_USBENSOFEN_MASK
#define USB0_ADDR USB0->ADDR
#define USB0_ISTAT USB0->ISTAT
#undef USB_ISTAT_SOFTOK
#define USB_ISTAT_SOFTOK USB_ISTAT_SOFTOK_MASK
#undef USB_ISTAT_TOKDNE
#define USB_ISTAT_TOKDNE USB_ISTAT_TOKDNE_MASK
#define USB0_STAT USB0->STAT
#undef USB_ISTAT_USBRST
#define USB_ISTAT_USBRST USB_ISTAT_USBRST_MASK
#undef USB_CTL_ODDRST
#define USB_CTL_ODDRST USB_CTL_ODDRST_MASK
#define USB0_ERRSTAT USB0->ERRSTAT
#define USB0_ERREN USB0->ERREN
#define USB0_INTEN USB0->INTEN
#undef USB_INTEN_TOKDNEEN
#define USB_INTEN_TOKDNEEN USB_INTEN_TOKDNEEN_MASK
#undef USB_INTEN_SOFTOKEN
#define USB_INTEN_SOFTOKEN USB_INTEN_SOFTOKEN_MASK
#undef USB_INTEN_STALLEN
#define USB_INTEN_STALLEN USB_INTEN_STALLEN_MASK
#undef USB_INTEN_ERROREN
#define USB_INTEN_ERROREN USB_INTEN_ERROREN_MASK
#undef USB_INTEN_USBRSTEN
#define USB_INTEN_USBRSTEN USB_INTEN_USBRSTEN_MASK
#undef USB_INTEN_SLEEPEN
#define USB_INTEN_SLEEPEN USB_INTEN_SLEEPEN_MASK
#undef USB_ISTAT_STALL
#define USB_ISTAT_STALL USB_ISTAT_STALL_MASK
#undef USB_ISTAT_ERROR
#define USB_ISTAT_ERROR USB_ISTAT_ERROR_MASK
#define USB0_ERRSTAT USB0->ERRSTAT
#undef USB_ISTAT_SLEEP
#define USB_ISTAT_SLEEP USB_ISTAT_SLEEP_MASK
#define SIM_SCGC4 SIM->SCGC4
#undef SIM_SCGC4_USBOTG
#define SIM_SCGC4_USBOTG SIM_SCGC4_USBOTG_MASK
#define USB0_BDTPAGE1 USB0->BDTPAGE1
#define USB0_BDTPAGE2 USB0->BDTPAGE2
#define USB0_BDTPAGE3 USB0->BDTPAGE3
#define USB0_OTGISTAT USB0->OTGISTAT
#define USB0_USBCTRL USB0->USBCTRL
#define USB0_CONTROL USB0->CONTROL
#undef USB_CONTROL_DPPULLUPNONOTG
#define USB_CONTROL_DPPULLUPNONOTG USB_CONTROL_DPPULLUPNONOTG_MASK
